api = "0.8"

[buildpack]
  id = "paketo-buildpacks/vsdbg"
  name = "Paketo Buildpack for Visual Studio Debugger"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/vsdbg/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml", "linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/amd64/bin/run", "linux/arm64/bin/build", "linux/arm64/bin/detect", "linux/arm64/bin/run"]
  pre-package = "./scripts/build.sh --target linux/amd64 --target linux/arm64"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:2f6e50b458436e450d36cf9549a6f552e8abbcab4708e38102d54d38fc164427"
    cpe = "cpe:2.3:a:microsoft:vsdbg:18.7.10421.2:*:*:*:*:*:*:*"
    id = "vsdbg"
    name = "Visual Studio Debugger"
    os = "linux"
    purl = "pkg:generic/vsdbg@18.7.10421.2?checksum=2f6e50b458436e450d36cf9549a6f552e8abbcab4708e38102d54d38fc164427&download_url=https://vsdebugger-cyg0dxb6czfafzaz.b01.azurefd.net/vsdbg-18-7-10421-2/vsdbg-linux-x64.tar.gz"
    source = "https://vsdebugger-cyg0dxb6czfafzaz.b01.azurefd.net/vsdbg-18-7-10421-2/vsdbg-linux-x64.tar.gz"
    source-checksum = "sha256:2f6e50b458436e450d36cf9549a6f552e8abbcab4708e38102d54d38fc164427"
    stacks = ["*"]
    uri = "https://vsdebugger-cyg0dxb6czfafzaz.b01.azurefd.net/vsdbg-18-7-10421-2/vsdbg-linux-x64.tar.gz"
    version = "18.7.10421+2"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:f58146c45c43a3166b898009547894650552a3ed7ff1771cff76a18bf10df771"
    cpe = "cpe:2.3:a:microsoft:vsdbg:18.7.10421.2:*:*:*:*:*:*:*"
    id = "vsdbg"
    name = "Visual Studio Debugger"
    os = "linux"
    purl = "pkg:generic/vsdbg@18.7.10421.2?checksum=f58146c45c43a3166b898009547894650552a3ed7ff1771cff76a18bf10df771&download_url=https://vsdebugger-cyg0dxb6czfafzaz.b01.azurefd.net/vsdbg-18-7-10421-2/vsdbg-linux-arm64.tar.gz"
    source = "https://vsdebugger-cyg0dxb6czfafzaz.b01.azurefd.net/vsdbg-18-7-10421-2/vsdbg-linux-arm64.tar.gz"
    source-checksum = "sha256:f58146c45c43a3166b898009547894650552a3ed7ff1771cff76a18bf10df771"
    stacks = ["*"]
    uri = "https://vsdebugger-cyg0dxb6czfafzaz.b01.azurefd.net/vsdbg-18-7-10421-2/vsdbg-linux-arm64.tar.gz"
    version = "18.7.10421+2"

  [[metadata.dependency-constraints]]
    constraint = "*"
    id = "vsdbg"
    patches = 1

[[stacks]]
  id = "*"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
